version: '3'
services:
  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    volumes:
      - ./mysql/mysql.d:/etc/mysql/conf.d
      - ../dump/mysql/:/var/lib/mysql
      - ./mysql/sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
      MYSQL_DATABASE: "app"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: 127.0.0.1
      

  postgres:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    volumes:
      - ../dump/postgres/:/var/lib/postgresql/data
#      - ./mysql/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: "postgres-user"
      POSTGRES_PASSWORD: "postgres-password"
      POSTGRES_DB: "rnddbname"

